### ISSUE TITLE
请求慢

### ISSUE THREAD

**Issue by jkjk6862** [hanximeng/LanzouAPI#15]
![Screenshot_2023-03-19-19-38-54-617_com android email](https://user-images.githubusercontent.com/97820649/226172831-48cea786-2748-4ab4-9598-b4239fff474f.jpg)
使用的是广州腾讯云2c2g4m轻量云服务器，是在国内的

自从上次无法请求修复之后就变得特别慢，之前感觉差不多一秒左右就好了

**Comment by hanximeng** [comment]
用服务器ping一下www.lanzoue.com

**Comment by jkjk6862** [comment]
![Screenshot_2023-03-19-21-51-31-795_com tencent mm](https://user-images.githubusercontent.com/97820649/226180563-4a0a75e9-220f-4870-bc0d-e93d22d428b6.jpg)

**Comment by hanximeng** [comment]
这就很奇怪

**Comment by jkjk6862** [comment]
会和php版本有关系吗？你的示例站点使用的php版本是什么

**Comment by hanximeng** [comment]
示例站点PHP是8.1，按道理来说应该是网络的问题，你可以尝试换一台服务器或者本地搭建环境测试一下，来排除网络问题
