### ISSUE TITLE
有计划支持蓝奏云轻享版吗

### ISSUE THREAD

**Issue by szkzn** [hanximeng/LanzouAPI#20]
蓝奏云官方新弄了个分支，蓝奏云轻享版，支持上传更大文件
域名：https://www.ilanzou.com/
已知目前部分格式（txt/pdf），在限定大小内（100MiB）支持免登录下载

希望大佬可以适配，是否有计划支持呢

**Comment by hanximeng** [comment]
暂无计划，后续再看看吧。
