### ISSUE TITLE
已超时，请刷新

### ISSUE THREAD

**Issue by szkzn** [hanximeng/LanzouAPI#4]
测试 URL，无密码外链：
a>https://www.lanzout.com/iEsza09fi9jg
b>https://0zgs.lanzout.com/iEsza09fi9jg
两者都是同一个文件，只是其中一个启用了个性化域名，均复现

PHP环境 v8.0.10，源码为当前 master 分支，搭建的API : https://t.0z.gs
浏览器  Chrome v99.0.4844.51（正式版本） （64 位）

使用你的 API：https://api.hanximeng.com/lanzou/?
也复现，报错类型一致
翻阅了之前的 issue，推测可能是不同地区线路可能别运营商劫持
测试线路：广东电信家宽、广州腾讯云 BGP 、北京腾讯云BGP、杭州阿里云BGP、东莞唯一网络 BGP、腾讯 AIA 国内 Anycast IP

![多地运营商线路测试](https://p.0z.gs/i/2022/08/12/62f5fdadda660.png)

{
    "code": 400,
    "msg": "已超时，请刷新"
}
![已超时请刷新](https://p.0z.gs/i/2022/08/12/62f5ff00ec6ad.png)

基本排除不是线路地区解析被劫持问题

测试更多样例 URL，每2个中，一个是个性化域名，另一个是没启用个性化域名，方便对比排查问题
https://0zgs.lanzout.com/i3xjofe
https://www.lanzout.com/i3xjofe

https://api.hanximeng.com/lanzou/?https://0zgs.lanzout.com/i3xjofe
https://api.hanximeng.com/lanzou/?https://www.lanzout.com/i3xjofe

https://www.lanzout.com/i5zvc4h
https://0zgs.lanzout.com/i5zvc4h

https://api.hanximeng.com/lanzou/?url=https://www.lanzout.com/i5zvc4h
https://api.hanximeng.com/lanzou/?url=https://0zgs.lanzout.com/i5zvc4h

测试一些设置了密码的外链，就没有这个问题，目前的样本数量测试表现 无密码外链 100% 超时

这些是 ok 的
https://api.hanximeng.com/lanzou/?url=https://0zgs.lanzout.com/Net-runtime-v606&pwd=6wu2
https://t.0z.gs/?url=https://0zgs.lanzout.com/Net-runtime-v606&pwd=6wu2

尝试手动更换为其他后缀 lanzoui lanzouu lanzouw lanzouf lanzouh 等，一样复现

**Comment by hanximeng** [comment]
已修复，感谢你详细的反馈，让我能迅速定位到问题。
