### ISSUE TITLE
来个赞赏码呗，希望能持续维护下去

### ISSUE THREAD

**Issue by szkzn** [hanximeng/LanzouAPI#5]
尽点微薄之力，之前这个项目的那个发起者大佬放弃了~
仅是个人使用代替部分博客场景提供的小文件下载

**Comment by hanximeng** [comment]
喜欢的话就点个 Star 吧，之前的我想应该说的是 MHanL 吧，之前有和他共同维护一段时间，现在依旧可以在本项目的贡献者中看到他，不出意外的话我会一直维护下去的，愿你使用愉快。
