### ISSUE TITLE
lanzou yun改版了，好像不生效了

### ISSUE THREAD

**Issue by renwfy** [hanximeng/LanzouAPI#7]
lanzou yun改版了，好像不生效了

**Comment by hanximeng** [comment]
请附上具体的失效文件的链接

**Comment by renwfy** [comment]
https://renwfy.lanzout.com/i7Eqy0fqk9vc

这个链接

**Comment by renwfy** [comment]
![QQ20221210-111051](https://user-images.githubusercontent.com/6526280/206826295-8cce4212-9a6d-4a6c-9934-7174eb822054.png)

你的测试地址
